-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 14:27:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema camagru
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema camagru
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `camagru` DEFAULT CHARACTER SET utf8 ;
USE `camagru` ;

-- -----------------------------------------------------
-- Table `camagru`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camagru`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NULL,
  `passeword` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `camagru`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camagru`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `dateCreated` DATETIME NULL,
  `online` INT NULL,
  `type` VARCHAR(255) NULL,
  `content` TEXT NULL,
  `salt` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NULL,
  `users_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users1_idx` (`users_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `camagru`.`configs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camagru`.`configs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `camagru`.`medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camagru`.`medias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `file` VARCHAR(255) NULL,
  `post_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medias_posts_idx` (`post_id` ASC))
ENGINE = MyISAM;

USE `camagru` ;

-- -----------------------------------------------------
-- Placeholder table for view `camagru`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camagru`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `camagru`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camagru`.`view2` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `camagru`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `camagru`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `camagru`.`view1`;
USE `camagru`;


-- -----------------------------------------------------
-- View `camagru`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `camagru`.`view2`;
USE `camagru`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
